export const unitTestCases = [
  {
    id: 'UT-ACT-001', module: 'Action extraction', scenario: 'Action item without owner',
    precondition: 'Normalized unstructured transcript', input: 'We need to update the server before Friday.',
    steps: 'Normalize transcript; extract action items.',
    expected: 'Owner is Unassigned, task is update the server, due date is Friday.',
    reference: 'tests/unit/actions.test.ts — keeps a required task without an owner as unassigned', status: 'PASS',
  },
  {
    id: 'UT-ACT-002', module: 'Action extraction', scenario: 'Multiple assignment styles',
    precondition: 'Format A transcript', input: 'Direct assignment, speaker commitment, and unowned requirement.',
    steps: 'Normalize transcript; extract all action items.',
    expected: 'Three distinct evidence-bound actions are returned with available owners and dates.',
    reference: 'tests/unit/actions.test.ts — extracts direct assignments, speaker commitments, and multiple actions', status: 'PASS',
  },
  {
    id: 'UT-ACT-003', module: 'Action extraction', scenario: 'Ordinary discussion is not an action',
    precondition: 'Normalized transcript', input: 'The team discussed the server capacity.',
    steps: 'Extract action items.', expected: 'No action item is returned.',
    reference: 'tests/unit/actions.test.ts — does not invent an action from ordinary discussion', status: 'PASS',
  },
  {
    id: 'UT-ACT-004', module: 'Action extraction', scenario: 'Thai assignment and deadline',
    precondition: 'Thai transcript', input: 'มาลี: สมชายจะส่งรายงานภายในวันศุกร์',
    steps: 'Normalize; extract action.', expected: 'Owner, task, and Friday deadline are extracted deterministically.',
    reference: 'tests/unit/actions.test.ts — supports a deterministic Thai owner, task, and weekday deadline pattern', status: 'PASS',
  },
  {
    id: 'UT-DEC-001', module: 'Decision extraction', scenario: 'Suggestions are not decisions',
    precondition: 'Option language only', input: 'Maybe Monday. Tuesday might be safer.',
    steps: 'Extract decisions.', expected: 'No final decision is returned.',
    reference: 'tests/unit/decisions.test.ts — does not convert suggestions or options into decisions', status: 'PASS',
  },
  {
    id: 'UT-DEC-002', module: 'Decision extraction', scenario: 'Explicit final decision',
    precondition: 'Transcript contains resolution language', input: 'We decided to launch on Friday.',
    steps: 'Extract decisions.', expected: 'Decision and exact supporting evidence are retained.',
    reference: 'tests/unit/decisions.test.ts — extracts explicit final decisions and retains evidence', status: 'PASS',
  },
  {
    id: 'UT-DEC-003', module: 'Decision extraction', scenario: 'Thai decision phrase',
    precondition: 'Thai transcript', input: 'สมชาย: เราตัดสินใจเปิดตัววันจันทร์',
    steps: 'Extract decisions.', expected: 'Explicit Thai decision is recognized.',
    reference: 'tests/unit/decisions.test.ts — recognizes a Thai explicit-decision phrase', status: 'PASS',
  },
  {
    id: 'UT-DEC-004', module: 'Decision extraction', scenario: 'Collective will decision',
    precondition: 'Transcript contains collective commitment', input: 'Alice: We will launch on Friday.',
    steps: 'Extract decisions.', expected: 'Launch on Friday is returned with the exact supporting utterance.',
    reference: 'tests/unit/decisions.test.ts — recognizes a collective will statement as an explicit decision', status: 'PASS',
  },
  {
    id: 'UT-DEC-005', module: 'Decision extraction', scenario: 'Tentative collective language',
    precondition: 'Collective will phrase is qualified as uncertain', input: 'Alice: Maybe we will launch on Friday.',
    steps: 'Extract decisions.', expected: 'No final decision is returned from the tentative statement.',
    reference: 'tests/unit/decisions.test.ts — does not promote a tentative collective will statement', status: 'PASS',
  },
  {
    id: 'UT-DEC-006', module: 'Decision extraction', scenario: 'Uncertainty after collective will',
    precondition: 'Collective statement contains an uncertainty qualifier', input: 'Alice: We will maybe launch on Friday.',
    steps: 'Extract decisions.', expected: 'No final decision is returned from the qualified commitment.',
    reference: 'tests/unit/decisions.test.ts — does not promote uncertainty inside a collective will statement', status: 'PASS',
  },
  {
    id: 'UT-DEC-007', module: 'Decision extraction', scenario: 'Commitment to consider',
    precondition: 'Collective statement commits only to consideration', input: 'Alice: We will consider launching on Friday.',
    steps: 'Extract decisions.', expected: 'No launch decision is returned from an option-evaluation statement.',
    reference: 'tests/unit/decisions.test.ts — does not promote a collective commitment to consider an option', status: 'PASS',
  },
  {
    id: 'UT-FLG-001', module: 'Problem detection', scenario: 'Meeting without a final decision',
    precondition: 'Multiple alternatives and no resolution', input: 'Monday, Tuesday, and Wednesday launch options.',
    steps: 'Extract decisions; detect flags.', expected: 'No-decision warning is present and no date is selected.',
    reference: 'tests/unit/flags.test.ts — flags a multi-option meeting with no final decision', status: 'PASS',
  },
  {
    id: 'UT-FLG-006', module: 'Problem detection', scenario: 'Non-date alternatives',
    precondition: 'Several technology options and no resolution', input: 'PostgreSQL, MySQL, and SQLite alternatives.',
    steps: 'Extract decisions; detect flags.', expected: 'No-decision warning appears without requiring date expressions.',
    reference: 'tests/unit/flags.test.ts — flags non-date alternatives without inventing a choice', status: 'PASS',
  },
  {
    id: 'UT-FLG-002', module: 'Problem detection', scenario: 'Conflicting dates',
    precondition: 'Common subject has unresolved dates', input: 'Go-live October 2; prepare for October 5.',
    steps: 'Detect problem flags.', expected: 'Conflict flag reports both unresolved dates.',
    reference: 'tests/unit/flags.test.ts — flags unresolved conflicting dates for a common go-live subject', status: 'PASS',
  },
  {
    id: 'UT-FLG-003', module: 'Problem detection', scenario: 'Resolved date options',
    precondition: 'Options followed by explicit resolution', input: 'Monday or Tuesday; final decision is Tuesday.',
    steps: 'Extract decision; detect flags.', expected: 'No unresolved date-conflict flag is returned.',
    reference: 'tests/unit/flags.test.ts — does not flag date options resolved by an explicit decision', status: 'PASS',
  },
  {
    id: 'UT-FLG-004', module: 'Problem detection', scenario: 'Unrelated action deadline',
    precondition: 'Release date and separate action deadline', input: 'Release next Friday; prepare server by Thursday.',
    steps: 'Extract actions; detect flags.', expected: 'Server deadline is excluded from release-date conflict candidates.',
    reference: 'tests/unit/flags.test.ts — does not treat an action deadline as a conflicting release date', status: 'PASS',
  },
  {
    id: 'UT-FLG-007', module: 'Problem detection', scenario: 'Unrelated topic dates',
    precondition: 'Launch and budget dates occur in separate topics', input: 'Launch Monday; budget review Tuesday.',
    steps: 'Detect problem flags by topic.', expected: 'No cross-topic date conflict is produced.',
    reference: 'tests/unit/flags.test.ts — does not combine dates from unrelated meeting topics into a conflict', status: 'PASS',
  },
  {
    id: 'UT-FLG-008', module: 'Problem detection', scenario: 'Unrelated general dated statement',
    precondition: 'A dated sentence follows a different topic without option language', input: 'Launch Monday; retrospective Tuesday.',
    steps: 'Detect problem flags by topic.', expected: 'The later sentence is not inherited into the launch topic or flagged as a conflict.',
    reference: 'tests/unit/flags.test.ts — does not inherit an unrelated general dated statement into the prior topic', status: 'PASS',
  },
  {
    id: 'UT-FLG-009', module: 'Problem detection', scenario: 'Unrelated modal dated statement',
    precondition: 'A tentative sentence follows a different topic but does not continue its subject', input: 'Launch Monday; retrospective might happen Tuesday.',
    steps: 'Detect problem flags by topic.', expected: 'No conflict or no-decision flag combines the unrelated statements.',
    reference: 'tests/unit/flags.test.ts — does not inherit an unrelated modal sentence into the prior topic', status: 'PASS',
  },
  {
    id: 'UT-FLG-010', module: 'Problem detection', scenario: 'Date-led alternative with another subject',
    precondition: 'A date-led option explicitly names an unrelated subject', input: 'Launch Monday; Tuesday might be safer for the retrospective.',
    steps: 'Detect problem flags by topic.', expected: 'No conflict or no-decision flag combines the unrelated statements.',
    reference: 'tests/unit/flags.test.ts — does not inherit a date-led alternative that names another subject', status: 'PASS',
  },
  {
    id: 'UT-FLG-011', module: 'Problem detection', scenario: 'Preparation statement with another subject',
    precondition: 'A preparation phrase explicitly names an unrelated subject', input: 'Launch Monday; prepare for retrospective on October 5.',
    steps: 'Detect problem flags by topic.', expected: 'No launch conflict is inferred from the unrelated preparation statement.',
    reference: 'tests/unit/flags.test.ts — does not inherit a preparation statement that names another subject', status: 'PASS',
  },
  {
    id: 'UT-FLG-005', module: 'Problem detection', scenario: 'Unassigned action warning',
    precondition: 'Ownerless action exists', input: 'We need to update the server.',
    steps: 'Extract actions; detect flags.', expected: 'Action remains unassigned and receives a visible warning.',
    reference: 'tests/unit/flags.test.ts — flags each unassigned action item without changing its owner', status: 'PASS',
  },
  {
    id: 'UT-NRM-001', module: 'Transcript normalization', scenario: 'Format A parsing',
    precondition: 'Speaker-colon transcript', input: 'Alice: Message', steps: 'Normalize transcript.',
    expected: 'Speaker and utterance are parsed as speaker-colon format.',
    reference: 'tests/unit/normalizer.test.ts — normalizes Format A speaker-colon lines and continuation text', status: 'PASS',
  },
  {
    id: 'UT-NRM-002', module: 'Transcript normalization', scenario: 'Format B parsing',
    precondition: 'Timestamped dash transcript', input: '[09:00] Alice - Message', steps: 'Normalize transcript.',
    expected: 'Timestamp, speaker, and text are parsed as timestamp-dash format.',
    reference: 'tests/unit/normalizer.test.ts — normalizes Format B timestamped dash lines', status: 'PASS',
  },
  {
    id: 'UT-NRM-003', module: 'Transcript normalization', scenario: 'Format C parsing',
    precondition: 'Timestamp-and-speaker blocks', input: '09:00 Alice then message on next line', steps: 'Normalize transcript.',
    expected: 'Header and body become one timestamp-block utterance.',
    reference: 'tests/unit/normalizer.test.ts — normalizes Format C timestamp-and-speaker blocks', status: 'PASS',
  },
  {
    id: 'UT-NRM-004', module: 'Transcript normalization', scenario: 'Missing speaker',
    precondition: 'Unlabelled text', input: 'We need to update the server.', steps: 'Normalize transcript.',
    expected: 'Text is preserved with a null speaker and unstructured format.',
    reference: 'tests/unit/normalizer.test.ts — keeps unlabelled text as one unknown-speaker utterance', status: 'PASS',
  },
  {
    id: 'UT-NRM-005', module: 'Transcript normalization', scenario: 'Empty transcript',
    precondition: 'Blank or BOM-only input', input: 'Whitespace/BOM', steps: 'Normalize transcript.',
    expected: 'No utterances are returned; processing does not throw.',
    reference: 'tests/unit/normalizer.test.ts — returns no utterances for blank or BOM-only input', status: 'PASS',
  },
  {
    id: 'UT-EXT-001', module: 'Meeting extraction', scenario: 'Duplicate participants and topics',
    precondition: 'Repeated speakers and two subject areas', input: 'Release and infrastructure fixture',
    steps: 'Normalize and extract meeting.', expected: 'Participants are deduplicated and topics remain separate.',
    reference: 'tests/unit/extractor.test.ts — deduplicates participants and separates release and infrastructure topics', status: 'PASS',
  },
  {
    id: 'UT-EXT-002', module: 'Meeting extraction', scenario: 'No invented participants',
    precondition: 'Unlabelled transcript', input: 'Ownerless requirement', steps: 'Extract meeting.',
    expected: 'Participants list is empty.',
    reference: 'tests/unit/extractor.test.ts — does not invent participants for unlabelled content', status: 'PASS',
  },
  {
    id: 'UT-EXT-003', module: 'Meeting extraction', scenario: 'Structured empty result',
    precondition: 'Empty normalized transcript', input: 'Empty text', steps: 'Extract meeting.',
    expected: 'Valid result with empty-transcript flag is returned.',
    reference: 'tests/unit/extractor.test.ts — returns a structured empty analysis instead of throwing', status: 'PASS',
  },
  {
    id: 'UT-EXT-004', module: 'Meeting extraction', scenario: 'Malformed control characters',
    precondition: 'Text includes controls', input: 'Malformed control-character content', steps: 'Normalize and extract.',
    expected: 'Pipeline does not crash and retains usable text.',
    reference: 'tests/unit/extractor.test.ts — handles malformed control characters without crashing', status: 'PASS',
  },
  {
    id: 'UT-SCH-001', module: 'Shared contracts', scenario: 'Valid structured analysis',
    precondition: 'Complete analysis object', input: 'Typed meeting result', steps: 'Parse with Zod schema.',
    expected: 'Schema accepts the result.',
    reference: 'tests/unit/contracts.test.ts — accepts a complete evidence-bound meeting result', status: 'PASS',
  },
  {
    id: 'UT-SCH-002', module: 'Shared contracts', scenario: 'Invalid empty action task',
    precondition: 'Action object has no task', input: 'Empty task string', steps: 'Parse with Zod schema.',
    expected: 'Schema rejects the action.',
    reference: 'tests/unit/contracts.test.ts — rejects action items without a task', status: 'PASS',
  },
  {
    id: 'IT-API-001', module: 'Analysis API', scenario: 'Analyze one transcript',
    precondition: 'Express app is available', input: 'format-a.txt multipart upload', steps: 'POST /api/analyze.',
    expected: 'Structured meeting, participants, topics, actions, and groups are returned.',
    reference: 'tests/api/analyze-api.test.ts — analyzes one transcript into structured results', status: 'PASS',
  },
  {
    id: 'IT-API-000', module: 'Analysis API', scenario: 'No-file request',
    precondition: 'Express app is available', input: 'Multipart request without files', steps: 'POST /api/analyze.',
    expected: 'HTTP 400 returns a safe prompt to select a transcript.',
    reference: 'tests/api/analyze-api.test.ts — rejects requests without files using a safe client message', status: 'PASS',
  },
  {
    id: 'IT-API-002', module: 'Analysis API', scenario: 'Partial batch failure',
    precondition: 'Valid TXT and unsupported file', input: 'Two multipart files', steps: 'POST /api/analyze.',
    expected: 'Valid result is preserved and unsupported file is reported independently.',
    reference: 'tests/api/analyze-api.test.ts — preserves valid results when another uploaded file is unsupported', status: 'PASS',
  },
  {
    id: 'IT-API-003', module: 'Analysis API', scenario: 'Empty file isolation',
    precondition: 'Valid TXT and empty TXT', input: 'Two multipart files', steps: 'POST /api/analyze.',
    expected: 'Valid meeting succeeds and empty file has its own failure.',
    reference: 'tests/api/analyze-api.test.ts — reports an empty file independently while processing another file', status: 'PASS',
  },
  {
    id: 'IT-API-004', module: 'Analysis API', scenario: 'Health endpoint',
    precondition: 'Express app is available', input: 'GET /api/health', steps: 'Request service readiness.',
    expected: 'HTTP 200 reports ready without internal implementation details.',
    reference: 'tests/api/analyze-api.test.ts — reports service readiness without exposing internals', status: 'PASS',
  },
  {
    id: 'IT-API-005', module: 'Analysis API', scenario: 'Oversized file isolation',
    precondition: 'Valid TXT and a TXT over 1 MiB', input: 'Two multipart files', steps: 'POST /api/analyze.',
    expected: 'Valid meeting succeeds and oversized file receives file-too-large failure.',
    reference: 'tests/api/analyze-api.test.ts — keeps valid results when another text file exceeds the application limit', status: 'PASS',
  },
  {
    id: 'IT-API-006', module: 'Analysis API', scenario: 'Invalid UTF-8 isolation',
    precondition: 'Valid TXT and invalid byte sequence', input: 'Two multipart files', steps: 'POST /api/analyze.',
    expected: 'Valid meeting succeeds and invalid text receives invalid-upload failure.',
    reference: 'tests/api/analyze-api.test.ts — reports invalid UTF-8 as a per-file upload failure', status: 'PASS',
  },
  {
    id: 'IT-API-007', module: 'Analysis API', scenario: 'Prototype-safe owner grouping',
    precondition: 'Owner name is Constructor', input: 'Constructor: I will prepare the release notes Friday.',
    steps: 'POST /api/analyze; inspect groupedActionItems.', expected: 'Constructor group contains the action and request succeeds.',
    reference: 'tests/api/analyze-api.test.ts — groups an owner whose name matches an object prototype property', status: 'PASS',
  },
  {
    id: 'IT-API-008', module: 'HTTP boundary', scenario: 'Same-origin policy',
    precondition: 'Health endpoint available', input: 'GET with attacker Origin header', steps: 'Request /api/health.',
    expected: 'Response does not grant Access-Control-Allow-Origin.',
    reference: 'tests/api/analyze-api.test.ts — does not opt arbitrary third-party origins into CORS', status: 'PASS',
  },
  {
    id: 'IT-RPT-000', module: 'Report API', scenario: 'Malformed report request',
    precondition: 'Express app is available', input: 'Invalid JSON body shape', steps: 'POST /api/report.',
    expected: 'HTTP 400 returns a safe validation error with no stack trace.',
    reference: 'tests/api/report-api.test.ts — rejects malformed report requests without a stack trace', status: 'PASS',
  },
  {
    id: 'IT-RPT-001', module: 'Report API', scenario: 'Word report export',
    precondition: 'Valid analysis batch', input: 'POST /api/report', steps: 'Generate and inspect returned ZIP.',
    expected: 'DOCX OOXML contains actual meeting results.',
    reference: 'tests/api/report-api.test.ts — returns a readable Word OOXML report containing actual results', status: 'PASS',
  },
  {
    id: 'CT-UI-001', module: 'Frontend', scenario: 'Additive deduplicated file queue',
    precondition: 'Application rendered', input: 'Two file-selection rounds with a duplicate',
    steps: 'Select files; click Analyze Meetings.', expected: 'Unique files remain queued and analysis starts only on explicit click.',
    reference: 'tests/frontend/app.test.tsx — adds files across selection rounds, avoids duplicates, and analyzes explicitly', status: 'PASS',
  },
  {
    id: 'CT-UI-002', module: 'Frontend', scenario: 'Accessible empty state',
    precondition: 'Application rendered with no files', input: 'No interaction', steps: 'Inspect upload and analysis controls.',
    expected: 'Empty-state guidance is visible and analysis action is disabled.',
    reference: 'tests/frontend/app.test.tsx — starts with an accessible empty upload state and disabled analysis action', status: 'PASS',
  },
  {
    id: 'CT-UI-003', module: 'Frontend', scenario: 'Client-side unsupported file feedback',
    precondition: 'Application rendered', input: 'notes.pdf', steps: 'Select unsupported file.',
    expected: 'Visible useful feedback appears before an upload request.',
    reference: 'tests/frontend/app.test.tsx — rejects unsupported files before upload and shows useful feedback', status: 'PASS',
  },
  {
    id: 'AT-DOC-001', module: 'Submission artifacts', scenario: 'SRS OOXML integrity',
    precondition: 'Generated SRS exists', input: 'Meeting_Notes_Distiller_SRS.docx', steps: 'Open ZIP entries; inspect document XML.',
    expected: 'Valid Word package contains required implemented-requirement sections.',
    reference: 'tests/artifacts/submission-documents.test.ts — includes a valid SRS Word document with implemented requirements', status: 'PASS',
  },
  {
    id: 'AT-XLS-001', module: 'Submission artifacts', scenario: 'Unit test workbook integrity',
    precondition: 'Generated workbook exists', input: 'Unit_Test_Cases.xlsx', steps: 'Open ZIP entries; inspect workbook and cell XML.',
    expected: 'Valid Excel package contains both mandatory edge-case scenarios.',
    reference: 'tests/artifacts/submission-documents.test.ts — includes a valid test-case workbook at docs/Unit_Test_Cases.xlsx', status: 'PASS',
  },
  {
    id: 'AT-XLS-002', module: 'Submission artifacts', scenario: 'SIT/UAT workbook integrity',
    precondition: 'Generated workbook exists', input: 'SIT_UAT_Test_Cases.xlsx', steps: 'Open ZIP entries; inspect workbook and cell XML.',
    expected: 'Valid Excel package contains upload and report workflows.',
    reference: 'tests/artifacts/submission-documents.test.ts — includes a valid test-case workbook at docs/SIT_UAT_Test_Cases.xlsx', status: 'PASS',
  },
  {
    id: 'AT-CAT-001', module: 'Submission artifacts', scenario: 'Test catalog synchronization',
    precondition: 'Catalog and test sources exist', input: 'scripts/test-catalog.mjs', steps: 'Check all suite source paths are referenced.',
    expected: 'Catalog remains linked to unit, API, component, artifact, and E2E source files.',
    reference: 'tests/artifacts/submission-documents.test.ts — keeps the documented test catalog synchronized with test source references', status: 'PASS',
  },
];

export const sitUatTestCases = [
  {
    id: 'SIT-001', module: 'Browser workflow', scenario: 'Upload and analyze one transcript',
    precondition: 'Frontend and backend running', input: 'format-a.txt',
    steps: 'Open app; choose file; click Analyze Meetings; wait for results.',
    expected: 'Meeting card shows filename, participants, topics, and Bob action.',
    reference: 'e2e/meeting-analysis.spec.ts — uploads and analyzes a transcript into structured meeting results', status: 'PASS',
  },
  {
    id: 'SIT-002', module: 'Browser workflow', scenario: 'Multiple additive uploads and owner grouping',
    precondition: 'Application is open', input: 'format-a.txt then missing-owner.txt',
    steps: 'Upload in two rounds; analyze.', expected: 'Both meetings appear; Bob and Unassigned owner groups appear.',
    reference: 'e2e/meeting-analysis.spec.ts — keeps additive upload rounds and groups actions by owner', status: 'PASS',
  },
  {
    id: 'SIT-003', module: 'Problem detection', scenario: 'No-decision browser warning',
    precondition: 'Application is open', input: 'no-decision.txt',
    steps: 'Upload; analyze; open problems view.', expected: 'Prominent no-decision warning appears and no final date is invented.',
    reference: 'e2e/meeting-analysis.spec.ts — shows a prominent no-decision warning without inventing a decision', status: 'PASS',
  },
  {
    id: 'SIT-004', module: 'Upload validation', scenario: 'Unsupported file rejection',
    precondition: 'Application is open', input: 'notes.pdf',
    steps: 'Select unsupported file.', expected: 'Useful validation message appears before any API request.',
    reference: 'e2e/meeting-analysis.spec.ts — rejects unsupported files before sending an analysis request', status: 'PASS',
  },
  {
    id: 'SIT-005', module: 'Report workflow', scenario: 'Download Word report',
    precondition: 'At least one meeting analyzed', input: 'format-a.txt',
    steps: 'Analyze; click Download Word Report; inspect download.', expected: 'A non-empty .docx ZIP with Word content is downloaded.',
    reference: 'e2e/meeting-analysis.spec.ts — downloads a structurally recognizable Word report', status: 'PASS',
  },
  {
    id: 'SIT-006', module: 'Analysis API', scenario: 'Mixed valid and invalid batch',
    precondition: 'API running', input: 'Valid TXT plus unsupported file', steps: 'POST multipart batch.',
    expected: 'HTTP 200 preserves successful meeting and reports failed filename.',
    reference: 'tests/api/analyze-api.test.ts — preserves valid results when another uploaded file is unsupported', status: 'PASS',
  },
  {
    id: 'UAT-001', module: 'User acceptance', scenario: 'User receives a useful meeting summary',
    precondition: 'Supported transcript available', input: 'format-a.txt', steps: 'Upload, analyze, review result card.',
    expected: 'User can identify participants, subject summary, and assigned work.',
    reference: 'e2e/meeting-analysis.spec.ts — uploads and analyzes a transcript into structured meeting results', status: 'PASS',
  },
  {
    id: 'UAT-002', module: 'User acceptance', scenario: 'User identifies missing ownership',
    precondition: 'Ownerless requirement transcript available', input: 'missing-owner.txt', steps: 'Upload with another meeting; analyze; review owner groups.',
    expected: 'Task appears under Unassigned and is visibly warned.',
    reference: 'e2e/meeting-analysis.spec.ts — keeps additive upload rounds and groups actions by owner', status: 'PASS',
  },
  {
    id: 'UAT-003', module: 'User acceptance', scenario: 'User identifies unresolved discussion',
    precondition: 'Transcript offers alternatives without resolution', input: 'no-decision.txt', steps: 'Upload; analyze; review warning.',
    expected: 'User sees no-decision status without an invented outcome.',
    reference: 'e2e/meeting-analysis.spec.ts — shows a prominent no-decision warning without inventing a decision', status: 'PASS',
  },
  {
    id: 'UAT-004', module: 'User acceptance', scenario: 'User exports analysis for sharing',
    precondition: 'Completed analysis', input: 'Analyzed meeting', steps: 'Click Download Word Report; open the file.',
    expected: 'Readable report contains the analyzed meeting and grouped actions.',
    reference: 'e2e/meeting-analysis.spec.ts — downloads a structurally recognizable Word report', status: 'PASS',
  },
];
